### ISSUE TITLE
Option to open a new lilyterm window from a Bash script?

### ISSUE THREAD

**Issue by MajorLunaC** [Tetralet/LilyTerm#105]
Lilyterm doesn't open a new terminal window when I run it from a bash script, but instead opens a new tab in an existing terminal window and doesn't even bring that terminal up to the front or make it active.

This causes major problems when I try to make a "dialog" interface, or run programs that should open a terminal. They're just hidden away and remain running without my knowledge.

Is there an option somewhere to deliberately open a new window, that I'm missing?

**Comment by xrat** [comment]
In my case, new windows open by default. You might want to provide more details like command line options of the 1st lilyterm process and of its children, plus respective profiles/config files you are using.

**Comment by MajorLunaC** [comment]
I didn't modify anything but colors. I recently compiled from this git.
Command line -> Opens new Window.
Bash Script -> Opens new Tab on the last existing Window.

Did you try a Bash script? I use it for a "terminal wrapper" of sorts, so whenever I click on a program to run, it runs it through the terminal wrapper script. Also does the same in a terminal if you run this:
lilyterm -x program-name file-name

**Comment by xrat** [comment]
> Bash Script -> Opens new Tab on the last existing Window

You mean something like the following opens a tab?
```
$ cat >lilywintest.sh
#!/bin/bash
lilyterm -x top
^D
$ chmod +x lilywintest.sh ; ./lilywintest.sh
```
But a plain `lilyterm` does not? Like
```
$ "lilyterm" -x top
```
That'd be strange indeed. Have you checked your profiles:
```
$ lilyterm --help | grep 'LilyTerm.*is:'
```

**Comment by MajorLunaC** [comment]
I could have sworn it did, but now it only opens new commands in tabs.

Now that I take yet another good hard look at all the config file options to make sure, yeah I completely didn't see that option.

# Launching executed command in a new tab instead of opening a new window.
execute_command_in_new_tab = 0

All fixed now. Sorry for all the trouble, and thanks for the help. I have to make sure to only check things in the late afternoon, not the morning.

**Comment by xrat** [comment]
Glad I was of some help. Since the maintainer of lilyterm seems to be busy these days you might want to close this issue yourself.
