### ISSUE TITLE
LilyTerm closes all tabs if i press [x] on tab

### ISSUE THREAD

**Issue by eleksir** [Tetralet/LilyTerm#134]
Hard to reproduce this issue.
Sometimes when i press [x] button on a tab LilyTerm closes. Maybe there issue with tab' [x] itself and click event get passed to window' "Close" button handler.

I catch this issue in i3wm.

**Comment by egmontkob** [comment]
Perhaps the same as https://github.com/lxde/lxterminal/issues/61 and https://bugs.launchpad.net/sakura/+bug/1790317?

**Comment by egmontkob** [comment]
There's a patch at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909469 (I haven't verified).

**Comment by shitpoet** [comment]
I confirm that the patch https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909469 works for lilyterm installed from Debian 10 Buster stable repo - lilyterm version 0.9.9.4+git20150208.f600c0-5.

**Comment by eleksir** [comment]
I apply the patch, mentioned by @egmontkob but there no change appear in particular this issue.

I'd like to notice that issue appears when tab is **selected**
To select the tab you need just click on it and dotted rectangle appears on tab. Now if you click [x] button on this selected tab whole window closes, not just selected tab.
