### ISSUE TITLE
Set TERM=xterm-256color

### ISSUE THREAD

**Issue by blueyed** [Tetralet/LilyTerm#74]
I have noticed that with `lilyterm -x vim` the colors where off, because Vim does not consider the terminal to support 256 colors in that case.

I have a workaround in my zshrc, but that gets not sourced with `lilyterm -x`.

Please consider setting `TERM=xterm-256color` by default.

See also issue #59 and the discussion therein.

**Comment by egmontkob** [comment]
Newest vte sets this by default, no extra action is required from the app.

**Comment by blueyed** [comment]
Thanks, closing.
