### ISSUE TITLE
Defining cursor shape and color from escape sequences

### ISSUE THREAD

**Issue by punassuming** [Tetralet/LilyTerm#9]
I have found that we can define the cursor color with escape sequences like that found in xterm, but have not been able to redefine the cursor shape.

For example, in xterm, I can use: `printf '\033]12;blue\007\033\033[4 q'` to change the cursor to blue and make it appear as an underscore.  Doing this in lilyterm makes the cursor blue, but not change the shape.

Is there a way of changing the cursor?

**Comment by tmccombs** [comment]
I'd also like to be able to have an application (such as neovim) change the shape of the cursor. See https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal
