### ISSUE TITLE
提供更改 /proc 路徑的選項

### ISSUE THREAD

**Issue by lantw44** [Tetralet/LilyTerm#92]
希望能提供 configure 選項，這樣才能在 FreeBSD 改用 /compat/linux/proc 而不用預設的 /proc。

**Comment by lantw44** [comment]
這看起來如果同時有 /proc 和 /compat/linux/proc 的時候還是不會找到 /compat/linux/proc ......

**Comment by Tetralet** [comment]
是說，應該 /compat/linux/proc > /proc 囉？

**Comment by lantw44** [comment]
因為 /proc 裡的東西很可能不是 LilyTerm 想要的那種格式 ......

**Comment by lantw44** [comment]
像是裡面可能沒有 stat
